feat(config): displayce config

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -9,6 +9,8 @@
 # otherwise, this config serves no purpose and we 'return'.
 [[ $- != *i* ]] && return
 
+fastfetch
+
 colors() {
 	local fgc bgc vals seq0
 
@@ -30,31 +32,37 @@ colors() {
 			seq0=${vals:+\e[${vals}m}
 			printf "  %-9s" "${seq0:-(default)}"
 			printf " ${seq0}TEXT\e[m"
-            printf ' \e[${vals:+${vals+$vals;}}1mBOLD\e[m'
+			printf ' \e[${vals:+${vals+$vals;}}1mBOLD\e[m'
 		done
-		echo; echo
+		echo
+		echo
 	done
 }
 
 tmp() {
-    $EDITOR `mktemp -u --suffix=.${1:-md}`
+	$EDITOR $(mktemp -u --suffix=.${1:-md})
 }
-fastfetch
 
 set -o vi # --> maybe, if I wanna have bash with vim shortcuts
 
-[ -f ~/.profile ] && . ~/.profile
+# Load profiles from ~/.profile.d
+if [ -d "$HOME/.profile.d/" ]; then
+	for profile in $HOME/.profile.d/*.sh; do
+		test -r "$profile" && . "$profile"
+	done
+	unset profile
+fi
 
 [ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
 
 # Change the window title of X terminals
 case ${TERM} in
-	xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|interix|konsole*)
-		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
-		;;
-	screen*)
-		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
-		;;
+xterm* | rxvt* | Eterm* | aterm | kterm | gnome* | interix | konsole*)
+	PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
+	;;
+screen*)
+	PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
+	;;
 esac
 
 use_color=true
@@ -64,16 +72,16 @@ use_color=true
 # instead of using /etc/DIR_COLORS.  Try to use the external file
 # first to take advantage of user additions.  Use internal bash
 # globbing instead of external grep binary.
-safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
+safe_term=${TERM//[^[:alnum:]]/?} # sanitize TERM
 match_lhs=""
-[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
+[[ -f ~/.dir_colors ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
 [[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
-[[ -z ${match_lhs}    ]] \
-	&& type -P dircolors >/dev/null \
-	&& match_lhs=$(dircolors --print-database)
+[[ -z ${match_lhs} ]] &&
+	type -P dircolors >/dev/null &&
+	match_lhs=$(dircolors --print-database)
 [[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true
 
-if ${use_color} ; then
+if ${use_color}; then
 	# .bashrc
 
 	# Uncomment the following line if you don't like systemctl's auto-paging feature:
@@ -87,55 +95,55 @@ if ${use_color} ; then
 	## Use a long listing format ##
 	PROMPT_COMMAND=__prompt_command # Func to gen PS1 after CMDs
 	__prompt_command() {
-	    local EXIT="$?"             # This needs to be first
-	    PS1=""
+		local EXIT="$?" # This needs to be first
+		PS1=""
 
-	    local RCol='\[\e[0m\]'
+		local RCol='\[\e[0m\]'
 
-	    local Red='\[\e[0;31m\]'
-	    local Gre='\[\e[0;32m\]'
-	    local BYel='\[\e[1;33m\]'
-	    local BBlu='\[\e[1;34m\]'
-	    local Pur='\[\e[0;35m\]'
+		local Red='\[\e[0;31m\]'
+		local Gre='\[\e[0;32m\]'
+		local BYel='\[\e[1;33m\]'
+		local BBlu='\[\e[1;34m\]'
+		local Pur='\[\e[0;35m\]'
 
-	    if [ $EXIT != 0 ]; then
-	        PS1+="${Red}\u${RCol}"      # Add red if exit code non 0
-	    else
-	        PS1+="${Gre}\u${RCol}"
-	    fi
-		branch=$(git branch 2> /dev/null | grep '^*' | colrm 1 2)
-	    PS1+=" [${EXIT}] ${BYel}\W ${BBlu}(${branch}) ${RCol}$ "
+		if [ $EXIT != 0 ]; then
+			PS1+="${Red}\u${RCol}" # Add red if exit code non 0
+		else
+			PS1+="${Gre}\u${RCol}"
+		fi
+		branch=$(git branch 2>/dev/null | grep '^*' | colrm 1 2)
+		PS1+=" [${EXIT}] ${BYel}\W ${BBlu}(${branch}) ${RCol}$ "
 	}
-  alias ls='lsd'
-  alias grep='grep --colour=auto'
-  alias egrep='egrep --colour=auto'
-  alias fgrep='fgrep --colour=auto'
-  alias ll='ls -lh'
-  alias l='ll -A'
-  alias la='ll -a'
-  alias gst='git status'
-  alias gaa='git add --all'
-  alias gc='git commit'
-  alias goi="rlwrap yaegi"
-  alias dc='git rev-parse --is-inside-work-tree >/dev/null && docker compose --file $(git rev-parse --show-toplevel)/dc-dev.yml'
-  alias gp='read -p "pushing on $(git branch --show-current) (<C-c> to cancel, <CR> to continue): " && git push'
-  alias gd="git diff"
-  alias gm="git merge"
-  alias gds="git diff --staged"
-  alias gc="git checkout"
-  alias gco='git commit'
-  alias gcl="git checkout-last-branch"
-  alias glf="git last-branches-fzf"
-  alias pull='git pull'
-  # alias cl="clear && printf '\e[3J'"
-  alias cl="clear"
-  alias speed='xset r rate 200 50'
-  alias again='exec bash'
-  alias commit-count='git log --oneline | wc -l '
-  alias commit-count-user='git shortlog -s'
+	alias ls='lsd'
+	alias grep='grep --colour=auto'
+	alias egrep='egrep --colour=auto'
+	alias fgrep='fgrep --colour=auto'
+	alias ll='ls -lh'
+	alias l='ll -A'
+	alias la='ll -a'
+	alias gst='git status'
+	alias gaa='git add --all'
+	alias gc='git commit'
+	alias goi="rlwrap yaegi"
+	alias dc='git rev-parse --is-inside-work-tree >/dev/null && docker compose --file $(git rev-parse --show-toplevel)/dc-dev.yml'
+	alias gp='read -p "pushing on $(git branch --show-current) (<C-c> to cancel, <CR> to continue): " && git push'
+	alias gd="git diff"
+	alias gm="git merge"
+	alias gds="git diff --staged"
+	alias gc="git checkout"
+	alias gco='git commit'
+	alias gcl="git checkout-last-branch"
+	alias glf="git last-branches-fzf"
+	alias pull='git pull'
+	# alias cl="clear && printf '\e[3J'"
+	alias cl="clear"
+	alias speed='xset r rate 200 50'
+	alias again='exec bash'
+	alias commit-count='git log --oneline | wc -l '
+	alias commit-count-user='git shortlog -s'
 
 else
-	if [[ ${EUID} == 0 ]] ; then
+	if [[ ${EUID} == 0 ]]; then
 		# show root@ when we don't have colors
 		PS1='\u@\h \W \$ '
 	else
@@ -145,15 +153,16 @@ fi
 
 unset use_color safe_term match_lhs sh
 
-alias cp="cp -i"                          # confirm before overwriting something
-alias df='df -h'                          # human-readable sizes
-alias free='free -m'                      # show sizes in MB
+alias cp="cp -i"     # confirm before overwriting something
+alias df='df -h'     # human-readable sizes
+alias free='free -m' # show sizes in MB
 alias np='nano -w PKGBUILD'
 alias mv='mv -i'
 alias cd='z'
 alias nv='nvim'
+alias bat='batcat'
 
-xhost +local:root > /dev/null 2>&1
+xhost +local:root >/dev/null 2>&1
 
 # Bash won't get SIGWINCH if another process is in the foreground.
 # Enable checkwinsize so that bash will check the terminal size when
@@ -171,32 +180,30 @@ shopt -s histappend
 #
 # # ex - archive extractor
 # # usage: ex <file>
-ex ()
-{
-  if [ -f $1 ] ; then
-    case $1 in
-      *.tar.bz2)   tar xjf $1   ;;
-      *.tar.gz)    tar xzf $1   ;;
-      *.bz2)       bunzip2 $1   ;;
-      *.rar)       unrar x $1   ;;
-      *.gz)        gunzip $1    ;;
-      *.tar)       tar xf $1    ;;
-      *.tbz2)      tar xjf $1   ;;
-      *.tgz)       tar xzf $1   ;;
-      *.zip)       unzip $1     ;;
-      *.Z)         uncompress $1;;
-      *.7z)        7z x $1      ;;
-      *)           echo "'$1' cannot be extracted via ex()" ;;
-    esac
-  else
-    echo "'$1' is not a valid file"
-  fi
+ex() {
+	if [ -f $1 ]; then
+		case $1 in
+		*.tar.bz2) tar xjf $1 ;;
+		*.tar.gz) tar xzf $1 ;;
+		*.bz2) bunzip2 $1 ;;
+		*.rar) unrar x $1 ;;
+		*.gz) gunzip $1 ;;
+		*.tar) tar xf $1 ;;
+		*.tbz2) tar xjf $1 ;;
+		*.tgz) tar xzf $1 ;;
+		*.zip) unzip $1 ;;
+		*.Z) uncompress $1 ;;
+		*.7z) 7z x $1 ;;
+		*) echo "'$1' cannot be extracted via ex()" ;;
+		esac
+	else
+		echo "'$1' is not a valid file"
+	fi
 }
-
-# . "$HOME/.cargo/env"
 
 export DENO_INSTALL="/home/lukac/.deno"
 export PATH="$PATH:$DENO_INSTALL/bin:/$HOME/.local/bin:/$HOME/Software/dbeaver"
+export PATH="$PATH:/$HOME/go/bin:$HOME/Software/bin/"
 export EDITOR="nvim"
 export _ZO_ECHO='1'
 
@@ -204,6 +211,12 @@ eval "$(zoxide init bash)"
 
 # forgit
 [ -f $HOME/Software/forgit/forgit.plugin.zsh ] && source $HOME/Software/forgit/forgit.plugin.zsh
+export TERM=xterm-256color
 
 # [ -f "/home/lukac/.ghcup/env" ] && source "/home/lukac/.ghcup/env" # ghcup-env
-source "${XDG_CONFIG_HOME:-$HOME/.config}/asdf-direnv/bashrc"
+export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
+export ASDF_DATA_DIR="$HOME/.asdf"
+. <(asdf completion bash)
+. <(just --completions bash)
+
+[ -f ~/.fzf.bash ] && source ~/.fzf.bash
